### ISSUE TITLE
Whar are the requirements to setup GMS Compat?

### ISSUE THREAD

**Issue by pixincreate** [VoltageOS/packages_apps_GmsCompat#1]
Hey, I'm planning of developing a Magisk module to add support for GMSCompat so that it can be used universally across vanilla ROMs that doesn't come up with GApps built-in.  

Are these 2 ([_packages_apps_GmsCompat_](https://github.com/VoltageOS/packages_apps_GmsCompat/issues), [_external_GmsCompatConfig_](https://github.com/VoltageOS/external_GmsCompatConfig)) enough to get GMSCompat working or do I need to add some patches to other files as well?   

Because when I asked Micay on twitter, he gave me set of [_commits list_](https://gist.github.com/thestinger/ee536cbd1ca674b94dde05831192c348) on twitter which he eventually added on grapheneOS gist that needs to be added into the ROM to get that working

_**P.S:** I'm new to Magisk module development. I'm just getting started with this._

**Comment by TheHardGamer** [comment]
Just as the commits list you included, Compat integration requires a number of changes across several repos and is not as simple as adding 2 packages, you might have to patch required libraries during module installation which is out of scope for this project.

**Comment by pixincreate** [comment]
Thank you for the response. I'm aware that my question was out of the scope for the project VoltageOS but I wanted to learn about the way this is implemented.  
I believe squashing and merging patches to the source is easier than making changes to already compiled ROM since I need to figure out what file does what..

**Comment by TheHardGamer** [comment]
> Thank you for the response. I'm aware that my question was out of the scope for the project VoltageOS but I wanted to learn about the way this is implemented. I believe squashing and merging patches to the source is easier than making changes to already compiled ROM since I need to figure out what file does what..

You will have to work out patching android runtime, bionic, etc libraries while installation since all of those patches are required, either way if you are a beginner then i would recommend starting with something easier.

**Comment by pixincreate** [comment]
> patching android runtime, bionic, etc libraries while installation

I've no idea about what all of these are. Looking forward to learn them.  

>  recommend starting with something easier

I wanted to start of with a easy one long time ago, that did not interest me much at that time. Felt incorporating GMSCompat on every android that is vanilla by default would be a game changer, started of right away without any second thought.   
Do you have any other suggestions for me to what files to look for after compilation? My other device (Lavender) is supported by this project, I believe, after installation, I can see the files with root access to test out..

**Comment by TheHardGamer** [comment]
> > patching android runtime, bionic, etc libraries while installation
> 
> I've no idea about what all of these are. Looking forward to learn them.
> 
> > recommend starting with something easier
> 
> I wanted to start of with a easy one long time ago, that did not interest me much at that time. Felt incorporating GMSCompat on every android that is vanilla by default would be a game changer, started of right away without any second thought. Do you have any other suggestions for me to what files to look for after compilation? My other device (Lavender) is supported by this project, I believe, after installation, I can see the files with root access to test out..

I cannot provide you a list of files, but it's fairly easy to figure out which files are being built.
For example, for this commit https://github.com/VoltageOS/art/commit/df04812791ba8eaf61da27a252dda33d640d4672, as you can see runtime/oat_file_manager.cc is being modified and its being built here https://github.com/VoltageOS/art/blob/fd5a84ea13719d4b58a197d3c42fd3f1672bdde0/runtime/Android.bp#L257

**Comment by pixincreate** [comment]
Got it. But after the ROM is built, when patching I'll not be having the code but the compiled ones in the `/root` dir right?  Do you mind elaborating that a bit? My doubt revolves around here -> [VoltageOS/art@df04812](https://github.com/VoltageOS/art/commit/df04812791ba8eaf61da27a252dda33d640d4672). Is it even possible to patch these kind of files. I'm asking because, one cannot access these files even with root access if I'm not wrong...   
Apologies if you think I'm wasting your time...
